#!/bin/sh
python /home/smilodon/craigslist-checker/craigslist.py "bicycle 49cm"
python /home/smilodon/craigslist-checker/craigslist.py "bicycle 50cm"
python /home/smilodon/craigslist-checker/craigslist.py "bicycle 52cm"
